### ISSUE TITLE
Hard-coding category

### ISSUE THREAD

**Issue by doingandlearning** [edieblu/mdfile-generator#1]
I love this! I've used it for a course I was doing notes on that had 32 lessons and it has helped loads!

The course I was doing had category 'react-native' and I noticed the category is hard-coded at the moment to 'react'. I fiddled around with a few quick fixes but couldn't find a quick way to get process.argv[3] to the IIFE.

I have forked this to come back and look at it later but also thought you might have already solved it :)

**Comment by edieblu** [comment]
Duh, I forgot to fix that, will see if I can find a solution (some issues with passing the process.argv I think). But if you figure it out, let me know! 😃

So glad it has helped you already! 🎉

**Comment by edieblu** [comment]
Fixed it! 🍾 I think 😅
Turns out you have to pass the arguments to the `evaluate()` function in the puppeteer.

Let me know if it works for you!

**Comment by doingandlearning** [comment]
That was it! Woohoo!!!!

**Comment by edieblu** [comment]
Aaaaaa legit hacker moment 😎 thanks Kevin!
