### ISSUE TITLE
Issue with video url - some characters are not converted

### ISSUE THREAD

**Issue by FabioRosado** [edieblu/mdfile-generator#3]
Hello Eva,

I've just encountered an issue with the video URL. I'm writing notes on a lesson that has the title: "Vim's different modes", the lesson URL is: `https://egghead.io/lessons/misc-vim-s-different-modes` but the generated one is `https://egghead.io/lessons/misc-vim's-different-modes`.

To fix this issue we just need to fix the regex on [line 89 ](https://github.com/edieblu/mdfile-generator/blob/ac783f0a8a901aa339388b32d4b3e81c2934f8e7/index.js#L89).

If you are happy with it, I will raise a PR to fix the issue. I'm just raising this Issue so I remember what we need to update 😄

**Comment by edieblu** [comment]
Excellent, go for it! 😃

Thanks!
